// CardSerialization.cs -- shared human-visible serialization for cards,
// potions, relics and character-specific state.
//
// Principle: every field here mirrors something a human player can see in
// the current UI (rendered card text, tooltips, visible counters). No RNG,
// no internal ids beyond the card/relic/potion id itself, no hidden
// counters, no future moves.
//
// Rendered text comes from the game's own localization + DynamicVar
// pipeline (CardModel.GetDescriptionForPile / GetDescriptionForUpgradePreview
// / potion.DynamicDescription / relic.DynamicDescription), so the numbers
// match what the player sees (e.g. "Deal 17 damage" after Strength).

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.Entities.Orbs;
using MegaCrit.Sts2.Core.Entities.Players;
using MegaCrit.Sts2.Core.Entities.Powers;
using MegaCrit.Sts2.Core.HoverTips;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Runs;

namespace STS2BridgeMod;

internal static class CardSerialization
{
    // ----------------------------------------------------------------
    // Text helpers
    // ----------------------------------------------------------------

    /// <summary>
    /// Strip BBCode markup ([img], [purple], ...) that the localization
    /// formatter leaves in rendered text, and normalize whitespace.
    /// </summary>
    public static string CleanText(string? text)
    {
        if (string.IsNullOrEmpty(text))
            return "";
        var cleaned = Regex.Replace(text, @"\[[^\]]*\]", "");
        cleaned = Regex.Replace(cleaned, @"\s+", " ").Trim();
        return cleaned;
    }

    private static string Safe(Func<string?> getter)
    {
        try
        {
            return CleanText(getter()) ?? "";
        }
        catch
        {
            return "";
        }
    }

    // ----------------------------------------------------------------
    // Powers (runtime tooltip + visibility, UI-equivalent path)
    // ----------------------------------------------------------------

    /// <summary>
    /// Serialize the powers of a creature the way the game UI shows them:
    /// only powers with IsVisible == true (PowerModel.HoverTips already
    /// returns an EMPTY list for hidden powers -- same filter the UI uses),
    /// with the description generated by the game's own HoverTips pipeline
    /// (smart/remote/dynamic variants included). No hardcoded glossary.
    /// </summary>
    public static List<Dictionary<string, object>> SerializePowers(Creature creature)
    {
        var result = new List<Dictionary<string, object>>();
        try
        {
            foreach (PowerModel power in creature.Powers)
            {
                try
                {
                    if (!power.IsVisible)
                        continue; // hidden mechanic power: human cannot see it either

                    var entry = new Dictionary<string, object>
                    {
                        ["id"] = power.Id.Entry,
                        ["name"] = Safe(() => power.Title.GetFormattedText()),
                        ["amount"] = power.Amount,
                        ["display_amount"] = power.DisplayAmount,
                    };
                    // UI-equivalent tooltip: the first hover tip is the
                    // power description generated by the game itself
                    // (smart/remote/dynamic variants resolved).
                    var tips = SerializeVisibleHoverTips(power.HoverTips);
                    if (tips.Count > 0 && tips[0].TryGetValue("description", out var desc))
                        entry["description"] = desc;
                    if (power.Type == PowerType.Debuff)
                        entry["debuff"] = true; // colour-coded in the UI
                    result.Add(entry);
                }
                catch { }
            }
        }
        catch (Exception ex)
        {
            Logger.Log("[CardSerialization] SerializePowers error: " + ex.Message);
        }
        return result;
    }

    /// <summary>
    /// Serialize hover tips the UI would show (title + description only --
    /// never icon/asset paths or internal ids).
    /// </summary>
    public static List<Dictionary<string, object>> SerializeVisibleHoverTips(
        IEnumerable<IHoverTip> tips)
    {
        var result = new List<Dictionary<string, object>>();
        if (tips == null)
            return result;
        foreach (var tip in tips)
        {
            try
            {
                // The concrete tips are HoverTip structs (IHoverTip only
                // exposes dedup metadata, not the human-visible text).
                if (tip is not HoverTip ht)
                    continue;
                var entry = new Dictionary<string, object>();
                var title = CleanText(ht.Title);
                var desc = CleanText(ht.Description);
                if (!string.IsNullOrEmpty(title))
                    entry["title"] = title;
                if (!string.IsNullOrEmpty(desc))
                    entry["description"] = desc;
                if (entry.Count > 0)
                    result.Add(entry);
            }
            catch { }
        }
        return result;
    }

    // ----------------------------------------------------------------
    // Act identity + bosses (map-screen-visible information)
    // ----------------------------------------------------------------

    /// <summary>
    /// Current act identity and its boss(es). The map screen shows the boss
    /// icon(s) for the current act with the name available on hover, so
    /// serializing the encounter display name is human-visible equivalence.
    /// The second boss is only included when the act actually has two bosses
    /// (RoomSet.HasSecondBoss), matching the two icons the UI draws.
    /// </summary>
    public static Dictionary<string, object>? SerializeActInfo(RunState runState)
    {
        try
        {
            ActModel act = runState.Act;
            if (act == null)
                return null;
            var info = new Dictionary<string, object>
            {
                ["act_id"] = act.Id.Entry,
                ["act_title"] = Safe(() => act.Title.GetFormattedText()),
            };
            var bosses = new List<Dictionary<string, object>>();
            void AddBoss(EncounterModel? encounter)
            {
                if (encounter == null)
                    return;
                var boss = new Dictionary<string, object>
                {
                    ["id"] = encounter.Id.Entry,
                    ["display_name"] = Safe(() => encounter.Title.GetFormattedText()),
                };
                bosses.Add(boss);
            }
            AddBoss(act.BossEncounter);
            if (act.HasSecondBoss)
                AddBoss(act.SecondBossEncounter);
            if (bosses.Count > 0)
                info["bosses"] = bosses;
            return info;
        }
        catch (Exception ex)
        {
            Logger.Log("[CardSerialization] SerializeActInfo error: " + ex.Message);
            return null;
        }
    }

    // ----------------------------------------------------------------
    // Cards
    // ----------------------------------------------------------------

    /// <summary>
    /// Full human-visible card serialization: current rendered text (the
    /// exact card face the player sees, with dynamic values resolved),
    /// current vs base costs (energy + stars), keywords, enchantment /
    /// affliction, upgrade level and optionally the game's own upgrade
    /// preview text.
    /// </summary>
    public static Dictionary<string, object> SerializeCardFull(
        CardModel card, bool includeUpgradePreview)
    {
        var data = new Dictionary<string, object>
        {
            ["id"] = card.Id.Entry,
            ["display_name"] = Safe(() => card.Title),
            ["type"] = card.Type.ToString(),
            ["rarity"] = card.Rarity.ToString(),
            ["target"] = card.TargetType.ToString(),
        };

        // Playability + human-readable unplayable reasons (the same flags
        // the engine uses to grey out / refuse the card in the UI).
        UnplayableReason reason;
        AbstractModel? preventer;
        bool playable = card.CanPlay(out reason, out preventer);
        data["playable"] = playable;
        if (!playable)
            data["unplayable_reasons"] = Describe(reason);

        // Energy cost: current (with all modifiers, as displayed) and base.
        try
        {
            if (card.EnergyCost.CostsX)
            {
                data["current_energy_cost"] = "X";
                data["base_energy_cost"] = "X";
            }
            else
            {
                data["current_energy_cost"] = card.EnergyCost.GetWithModifiers(CostModifiers.All);
                data["base_energy_cost"] = card.EnergyCost.Canonical;
            }
        }
        catch
        {
            data["current_energy_cost"] = card.EnergyCost.Canonical;
            data["base_energy_cost"] = card.EnergyCost.Canonical;
        }

        // Star cost (Regent) -- only present when the card actually has one,
        // exactly like the UI only shows a star icon on such cards.
        try
        {
            if (card.HasStarCostX)
            {
                data["current_star_cost"] = "X";
            }
            else if (card.CurrentStarCost >= 0)
            {
                data["current_star_cost"] = card.GetStarCostWithModifiers();
                data["base_star_cost"] = card.CurrentStarCost;
            }
        }
        catch { }

        // Upgrade level (>1 supported by some cards).
        data["upgraded"] = card.IsUpgraded;
        try
        {
            if (card.CurrentUpgradeLevel > 0)
                data["upgrade_level"] = card.CurrentUpgradeLevel;
        }
        catch { }

        // Current rendered card text: this is what the player actually sees
        // (dynamic damage/block/etc. already resolved). The game's own
        // upgrade preview text, where the UI offers one.
        string displayText = Safe(() => card.GetDescriptionForPile(PileType.Hand));
        if (string.IsNullOrEmpty(displayText))
            displayText = Safe(() => card.GetDescriptionForPile(PileType.None));
        if (!string.IsNullOrEmpty(displayText))
            data["current_display_text"] = displayText;

        if (includeUpgradePreview && card.IsUpgradable)
        {
            string preview = Safe(() => card.GetDescriptionForUpgradePreview());
            if (!string.IsNullOrEmpty(preview))
                data["upgrade_preview_text"] = preview;
        }

        // Target-specific previews: for cards that require a selectable
        // target and have 2+ living targets, the game UI shows a different
        // dynamic-var preview while hovering each target. We reuse exactly
        // that public render path (GetDescriptionForPile with the target),
        // which is the same call NCard's targeting preview makes. It is a
        // read-only render: no RNG is consumed, no game action runs, and
        // no live state is committed. Only emitted when the previews are
        // NOT identical (otherwise one line suffices).
        if (card.TargetType == TargetType.AnyEnemy)
        {
            try
            {
                var combatState = card.CombatState;
                if (combatState != null)
                {
                    var targets = combatState.HittableEnemies
                        .Where(c => c.IsAlive).ToList();
                    if (targets.Count >= 2)
                    {
                        var previews = new List<Dictionary<string, object>>();
                        var texts = new HashSet<string>();
                        foreach (var target in targets)
                        {
                            var text = Safe(() =>
                                card.GetDescriptionForPile(PileType.Hand, target));
                            if (string.IsNullOrEmpty(text))
                                continue;
                            texts.Add(text);
                            previews.Add(new Dictionary<string, object>
                            {
                                ["enemy_id"] = target.IsMonster
                                    ? target.Monster!.Id.Entry : "UNKNOWN",
                                ["enemy_name"] = target.IsMonster
                                    ? Safe(() => target.Monster!.Title.GetFormattedText())
                                    : "",
                                ["displayed_text"] = text,
                            });
                        }
                        if (previews.Count >= 2 && texts.Count > 1)
                            data["target_previews"] = previews;
                        else if (previews.Count >= 2)
                            data["target_preview_identical"] = true;
                    }
                }
            }
            catch { }
        }

        // Hover information for the card's keywords / enchantment /
        // affliction, straight from the game's hover-tip pipeline (the same
        // tips the UI shows on hover). The card face text already includes
        // the keyword names; these are the full visible definitions.
        try
        {
            var hoverInfo = SerializeVisibleHoverTips(card.HoverTips)
                .Where(t => t.ContainsKey("title"))
                .ToList();
            if (hoverInfo.Count > 0)
                data["hover_info"] = hoverInfo;
        }
        catch { }

        // Keywords (visible on the card / hover tooltip).
        try
        {
            var keywords = card.Keywords.Select(k => k.ToString()).ToList();
            if (keywords.Count > 0)
                data["keywords"] = keywords;
        }
        catch { }

        // Enchantment / affliction: full visible text. Both change the
        // card's identity for the player; the current_display_text already
        // includes their extra lines, but the names are kept explicit.
        try
        {
            if (card.Enchantment != null)
            {
                data["enchantment"] = new Dictionary<string, object>
                {
                    ["id"] = card.Enchantment.Id.Entry,
                    ["name"] = Safe(() => card.Enchantment.Title.GetFormattedText()),
                    ["description"] = Safe(() => card.Enchantment.DynamicDescription.GetFormattedText()),
                };
            }
        }
        catch { }
        try
        {
            if (card.Affliction != null)
            {
                var affliction = new Dictionary<string, object>
                {
                    ["id"] = card.Affliction.Id.Entry,
                    ["name"] = Safe(() => card.Affliction.Title.GetFormattedText()),
                    ["description"] = Safe(() => card.Affliction.DynamicDescription.GetFormattedText()),
                };
                try { affliction["amount"] = card.Affliction.Amount; } catch { }
                data["affliction"] = affliction;
            }
        }
        catch { }

        return data;
    }

    private static List<string> Describe(UnplayableReason reason)
    {
        var parts = new List<string>();
        foreach (UnplayableReason flag in Enum.GetValues(typeof(UnplayableReason)))
        {
            if (flag != UnplayableReason.None && reason.HasFlag(flag))
                parts.Add(flag.ToString());
        }
        return parts;
    }

    // ----------------------------------------------------------------
    // Character-specific visible state (explicit namespace)
    // ----------------------------------------------------------------

    /// <summary>
    /// Everything the character's human player can currently see about
    /// character-specific resources. Visibility follows the game's own UI
    /// rules (NStarCounter shows the star counter when
    /// Character.ShouldAlwaysShowStarCounter or Stars &gt; 0; orb slots
    /// exist only when BaseOrbSlotCount &gt; 0; Osty is a Necrobinder pet),
    /// never hardcoded guesses.
    /// Python renders this namespace generically.
    /// </summary>
    public static Dictionary<string, object>? BuildVisibleCharacterState(Player player)
    {
        try
        {
            var pcs = player.PlayerCombatState;
            var creature = player.Creature;
            var state = new Dictionary<string, object>();

            // Star counter (Regent): exact same visibility rule as
            // NStarCounter.cs in the game UI.
            if (pcs != null)
            {
                try
                {
                    if (player.Character.ShouldAlwaysShowStarCounter || pcs.Stars > 0)
                        state["stars"] = pcs.Stars;
                }
                catch { }
            }

            // Orb slots (Defect): ordered, with UI-visible passive/evoke
            // values; empty slots included, in UI order.
            if (pcs != null && player.BaseOrbSlotCount > 0)
            {
                try
                {
                    PowerModel? focus = creature?.Powers.FirstOrDefault(
                        p => string.Equals(p.Id.Entry, "FOCUS", StringComparison.OrdinalIgnoreCase));
                    if (focus != null)
                        state["focus"] = focus.Amount;
                }
                catch { }

                try
                {
                    OrbQueue queue = pcs.OrbQueue;
                    var orbs = new List<Dictionary<string, object>>();
                    for (int i = 0; i < queue.Capacity; i++)
                    {
                        if (i < queue.Orbs.Count)
                        {
                            OrbModel orb = queue.Orbs[i];
                            orbs.Add(new Dictionary<string, object>
                            {
                                ["slot"] = i,
                                ["type"] = orb.Id.Entry,
                                ["passive"] = orb.PassiveVal,
                                ["evoke"] = orb.EvokeVal,
                            });
                        }
                        else
                        {
                            orbs.Add(new Dictionary<string, object> { ["slot"] = i, ["empty"] = true });
                        }
                    }
                    state["orb_slots"] = orbs;
                    state["orb_slot_capacity"] = queue.Capacity;
                }
                catch { }
            }

            // Osty (Necrobinder's pet): only for the character that has one,
            // mirroring the UI that always shows Osty's status for Necro.
            if (player.Character is MegaCrit.Sts2.Core.Models.Characters.Necrobinder)
            {
                try
                {
                    Creature? osty = player.Osty;
                    var ostyData = new Dictionary<string, object>
                    {
                        ["present"] = osty != null,
                        ["alive"] = osty != null && osty.IsAlive,
                    };
                    if (osty != null)
                    {
                        ostyData["hp"] = osty.CurrentHp;
                        ostyData["max_hp"] = osty.MaxHp;
                        ostyData["block"] = osty.Block;
                        var powers = new List<Dictionary<string, object>>();
                        foreach (PowerModel power in osty.Powers)
                        {
                            powers.Add(new Dictionary<string, object>
                            {
                                ["id"] = power.Id.Entry,
                                ["amount"] = power.Amount,
                            });
                        }
                        if (powers.Count > 0)
                            ostyData["powers"] = powers;
                    }
                    state["osty"] = ostyData;
                }
                catch { }
            }

            return state.Count > 0 ? state : null;
        }
        catch (Exception ex)
        {
            Logger.Log("[CardSerialization] visible_character_state error: " + ex.Message);
            return null;
        }
    }
}
